version: 2

updates:
  # Flutter / Dart packages
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Singapore"

    target-branch: "main"

    open-pull-requests-limit: 5

    rebase-strategy: "auto"

    commit-message:
      prefix: "deps(pub)"

    labels:
      - "dependencies"
      - "flutter"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:10"
      timezone: "Asia/Singapore"

    target-branch: "main"

    open-pull-requests-limit: 5

    rebase-strategy: "auto"

    commit-message:
      prefix: "deps(ci)"

    labels:
      - "dependencies"
      - "github-actions"

  # Android Gradle
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:20"
      timezone: "Asia/Singapore"

    target-branch: "main"

    open-pull-requests-limit: 5

    rebase-strategy: "auto"

    commit-message:
      prefix: "deps(android)"

    labels:
      - "dependencies"
      - "android"

