
# 自动为 PR 添加标签

# 示例：根据文件路径添加标签
# documentation: # 标签名称
#   - ".github/ISSUE_TEMPLATE/*"
#   - "docs/**/*"
#   - "README.md"

# feature: # 标签名称
#   - "lib/src/features/**/*.dart"

# bug: # 标签名称
#   - "lib/src/bugs/**/*.dart"

# ci: # 标签名称
#   - ".github/workflows/**/*"

# dependencies: # 标签名称
#   - "pubspec.yaml"
#   - "pubspec.lock"

# size/S: # 小尺寸 PR
#   - ".github/scripts/pr-size.sh"

# size/M:
#   - ".github/scripts/pr-size.sh"

# size/L:
#   - ".github/scripts/pr-size.sh"

# size/XL:
#   - ".github/scripts/pr-size.sh"

# 可以根据项目实际情况自定义更多标签规则
